
BASE="https://img.shields.io/badge/"
SUFFIX="?style=flat-square"

all: status-alpha-green.svg status-done-brightgreen.svg status-in_progress-yellow.svg status-planning-red.svg

%.svg:
	wget "$(BASE)$@$(SUFFIX)" "--output-document=$@"




